server:
  port: 8488

# 数据库信息配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/website
    username: root
    password: 123456

# mybatis信息配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

# 日志信息配置
logging:
  level:
    root: info
  file:
    name: comment.log