server:
  port: 8488

# 数据库信息配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.186.21:3306/website?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

# mybatis信息配置
mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:dao/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

# 日志信息配置
logging:
  level:
    root: info
  file:
    name: comment.log